name: Frontend Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CSSLint
      run: |
        sudo apt-get update
        sudo apt-get install -y npm
        sudo npm install -g csslint

    - name: Lint CSS
      run: csslint CollaborativeEditor/style.css || true

    - name: Install JSHint
      run: npm install -g jshint

    - name: Lint JavaScript
      run: jshint CollaborativeEditor/script.js || true
